'use client';

import { useCallback, useEffect, useState } from 'react';
import {
	fetchCspPartnerAnalyticsByCountry,
	fetchCspPartnerAnalyticsFilterOptions,
	fetchCspPartnerAnalyticsSkuPieGrid,
	fetchCspPartnerAnalyticsTileCounts,
	type CspPartnerAnalyticsByCountryRow,
	type CspPartnerAnalyticsFilterOptions,
	type CspPartnerAnalyticsRange,
	type CspPartnerAnalyticsSkuPieGridBox,
	type CspPartnerAnalyticsTileCounts,
} from './csp-partner-analytics-api';
import { CspPartnerAnalyticsByCountryChart } from './csp-partner-analytics-by-country-chart';
import { CspPartnerAnalyticsFiltersBar } from './csp-partner-analytics-filters-bar';
import {
	CspPartnerAnalyticsSkuByCountryChart,
	type SkuTab,
} from './csp-partner-analytics-sku-by-country-chart';
import { CspPartnerAnalyticsSkuPieGrid } from './csp-partner-analytics-sku-pie-grid';
import { CspPartnerAnalyticsTiles } from './csp-partner-analytics-tiles';

const START_SKU_TABS: SkuTab[] = [
	{ id: 'bb', label: 'Business Basic' },
	{ id: 'bs', label: 'Business Standard' },
	{ id: 'bp', label: 'Business Premium' },
	{ id: 'other', label: 'Other' },
];

const END_SKU_TABS: SkuTab[] = [
	{ id: 'bs_cb', label: 'BS + Copilot' },
	{ id: 'bp_cb', label: 'BP + Copilot' },
	{ id: 'bp_cb_purview', label: 'BP + Copilot + Purview' },
	{ id: 'bp_defender', label: 'BP + Defender' },
	{ id: 'bp_purview', label: 'BP + Purview' },
	{ id: 'bp_defender_purview', label: 'BP + Defender + Purview' },
];

export function CspPartnerAnalyticsClient() {
	const [range, setRange] = useState<CspPartnerAnalyticsRange>('7d');
	const [partnerOrgId, setPartnerOrgId] = useState<string | null>(null);
	const [countries, setCountries] = useState<string[]>([]);

	const [tileCounts, setTileCounts] =
		useState<CspPartnerAnalyticsTileCounts | null>(null);
	const [filterOptions, setFilterOptions] =
		useState<CspPartnerAnalyticsFilterOptions | null>(null);
	const [byCountry, setByCountry] = useState<
		CspPartnerAnalyticsByCountryRow[]
	>([]);
	const [skuPieGrid, setSkuPieGrid] = useState<
		CspPartnerAnalyticsSkuPieGridBox[]
	>([]);
	const [loading, setLoading] = useState(false);
	const [error, setError] = useState<string | null>(null);

	const loadData = useCallback(async () => {
		const filters = { range, partnerOrgId, countries };
		setLoading(true);
		setError(null);
		try {
			const [counts, options, byCountrySeries, pieGrid] = await Promise.all([
				fetchCspPartnerAnalyticsTileCounts(filters),
				fetchCspPartnerAnalyticsFilterOptions(filters),
				fetchCspPartnerAnalyticsByCountry(filters),
				fetchCspPartnerAnalyticsSkuPieGrid(filters),
			]);
			setTileCounts(counts);
			setFilterOptions(options);
			setByCountry(byCountrySeries);
			setSkuPieGrid(pieGrid);
		} catch (err) {
			setError(err instanceof Error ? err.message : 'Failed to load analytics');
		} finally {
			setLoading(false);
		}
	}, [range, partnerOrgId, countries]);

	useEffect(() => {
		void loadData();
	}, [loadData]);

	useEffect(() => {
		if (!filterOptions) return;
		if (
			partnerOrgId &&
			!filterOptions.partners.some((p) => p.orgId === partnerOrgId)
		) {
			setPartnerOrgId(null);
		}
		if (countries.length > 0) {
			const filtered = countries.filter((c) =>
				filterOptions.countries.includes(c),
			);
			if (filtered.length !== countries.length) {
				setCountries(filtered);
			}
		}
	}, [filterOptions, partnerOrgId, countries]);

	return (
		<div
			className="mx-auto flex w-full max-w-[1440px] flex-col gap-4 px-6 py-6"
			data-testid="csp-partner-analytics-client"
		>
			<header className="flex flex-col gap-1">
				<h1 className="text-2xl font-semibold text-stone-950">
					CSP Partner Analytics
				</h1>
				<p className="text-sm text-stone-500">
					Cross-partner usage of the CSP partner portal.
				</p>
			</header>

			<CspPartnerAnalyticsFiltersBar
				range={range}
				partnerOrgId={partnerOrgId}
				countries={countries}
				options={filterOptions}
				onRangeChange={setRange}
				onPartnerChange={setPartnerOrgId}
				onCountriesChange={setCountries}
			/>

			{error ? (
				<div className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">
					{error}
				</div>
			) : null}

			<div className="space-y-1.5 rounded-2xl bg-(--ds-color-sea-salt-100) p-1.5">
				<CspPartnerAnalyticsTiles
					data={tileCounts}
					loading={loading}
					countryFilterActive={countries.length > 0}
				/>
				<CspPartnerAnalyticsByCountryChart
					data={byCountry}
					loading={loading}
				/>
				<CspPartnerAnalyticsSkuByCountryChart
					title="Proposals generated by End SKU"
					dimension="end"
					tabs={END_SKU_TABS}
					filters={{ range, partnerOrgId, countries }}
					color="var(--color-blue-800)"
					testId="csp-partner-analytics-end-sku-chart"
				/>
				<CspPartnerAnalyticsSkuByCountryChart
					title="Proposals generated by Start SKU"
					dimension="start"
					tabs={START_SKU_TABS}
					filters={{ range, partnerOrgId, countries }}
					color="var(--color-blue-600)"
					testId="csp-partner-analytics-start-sku-chart"
				/>
				<CspPartnerAnalyticsSkuPieGrid data={skuPieGrid} loading={loading} />
			</div>
		</div>
	);
}
