export {
	buildProposalScenarios,
	buildRegionalPricingContext,
	buildRegionalPricingContextForRegions,
	calculateScenarioAnnualValuesFromPrices,
	calculateScenarioFromExplicitPrices,
	calculateIncentives,
	calculateScenario,
	convertUsdAmountToRegional,
	DEFAULT_CURRENT_SKU_MARGIN_PERCENT,
	deriveMarginPercentFromPrices,
	deriveResellerPriceFromMargin,
	getDefaultTargetSkuMarginPercent,
	getRegionalStartingSkuMonthlyPrice,
	getStrategicAcceleratorRate,
	getValidUpgradePaths,
	matchStartingSku,
	normalizeProduct,
	normalizeNonNegativeMoney,
	normalizeSeats,
	annualizeMonthlyPrice,
	resolveCountryFromRegion,
	roundCurrency,
	STARTING_SKUS,
	type CalculateScenarioOptions,
	type ProposalScenario,
	type RegionalPricingContext,
	type ScenarioExplicitAnnualValues,
	type ScenarioExplicitMonthlyPrices,
	type ScenarioJourney,
} from '@repo/shared';
